### ISSUE TITLE
Change Clickhouse Setting 

### ISSUE THREAD

**Issue by orchie** [EdurtIO/dbm#102]
I find the feature at DATAgrip
<img src="https://img-blog.csdnimg.cn/20201224172519276.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2ZiaF81MjA=,size_16,color_FFFFFF,t_70">

Maybe this  modify system table ,but its very useful!

and other , if press "ctrl+enter" can exec sql hot key ,it will be better.
thanks!

**Comment by qianmoQ** [comment]
Thanks for the suggestions and we will support them in part in the next version

**Comment by qianmoQ** [comment]
not implemented https://github.com/ClickHouse/ClickHouse/issues/4548
