### ISSUE TITLE
bug: DDL grammar 

### ISSUE THREAD

**Issue by 24kGarry** [EdurtIO/dbm#188]
when I execute `'insert  into table xxxxx'`, display error 
`"Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected '(' before: 'FORMAT JSON': at row 1 (version 20.8.3.18)"`,  need to add a semicolon ';' to execute.

**Comment by qianmoQ** [comment]
This is because ClickHouse does not support INSERT formatting using the Http interface.
