### ISSUE TITLE
It would be nice to have a runable docker container

### ISSUE THREAD

**Issue by olafbuitelaar** [EdurtIO/dbm#37]
I tried to create a basic docker container based on node:16/node:16-alphine, and the latest tag 1.6.0, but the "yarn run build" fails on;
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/views/Data/Metadata/index.vue
    Module not found: Error: Can't resolve '../../components/table/TableCreate' in '/dbm/src/renderer/views/Data/Metadata'
     @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/views/Data/Metadata/index.vue 13:0-61
     @ ./src/renderer/views/Data/Metadata/index.vue
     @ ./src/renderer/router/index.js
     @ ./src/renderer/main.js

**Comment by qianmoQ** [comment]
In which branch is the source code?

**Comment by olafbuitelaar** [comment]
It's from the master branch tag 1.6.0 (commit: 21a4965). I also had tried the 1.5.0 and 1.4.0, but none seem to pass the `yarn run build` or `yarn run dev`

**Comment by qianmoQ** [comment]
> It's from the master branch tag 1.6.0 (commit: [21a4965](https://github.com/EdurtIO/dbm/commit/21a4965496de53483919ac476c94f9e36b7674fa)). I also had tried the 1.5.0 and 1.4.0, but none seem to pass the `yarn run build` or `yarn run dev`

Could you please send your Dockerfile configuration

**Comment by olafbuitelaar** [comment]
Well i was actually just poking around in the standard node container via; `docker run -it --entrypoint bash node:16`
quickly whipped this docker file, which is essentially what i've done (beside all debugging, and trying to find if there was a dependency issue, as with <1.6.0 i receive this error;/dbm/node_modules/electron/dist/electron: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory (amongst some more error's))
so tried to install ; apt-get -y install --no-install-recommends xorg openbox libnss3 libasound2 libatk-adaptor libgtk-3-0  libgconf-2-4

```Dockerfile

FROM node:16

RUN git clone --branch 1.6.0 https://github.com/EdurtIO/dbm.git && cd dbm && npm install -g node-sass && yarn install && yarn run build
```

**Comment by qianmoQ** [comment]
> Well i was actually just poking around in the standard node container via; `docker run -it --entrypoint bash node:16` quickly whipped this docker file, which is essentially what i've done (beside all debugging, and trying to find if there was a dependency issue, as with <1.6.0 i receive this error;/dbm/node_modules/electron/dist/electron: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory (amongst some more error's)) so tried to install ; apt-get -y install --no-install-recommends xorg openbox libnss3 libasound2 libatk-adaptor libgtk-3-0 libgconf-2-4
> 
> ```dockerfile
> FROM node:16
> 
> RUN git clone --branch 1.6.0 https://github.com/EdurtIO/dbm.git && cd dbm && npm install -g node-sass && yarn install && yarn run build
> ```

Okay, I'll check it. Maybe the electron doesn't fit docker

**Comment by qianmoQ** [comment]
@24kGarry 

What is the final result status of this Issues?

**Comment by olafbuitelaar** [comment]
What errors do you encounter? when i try to build the container, i receive the initial posted error.

**Comment by 24kGarry** [comment]
> What errors do you encounter? when i try to build the container, i receive the initial posted error.

firstly, when I docker build it , it can't  generate the 'dockerfile' and reports the error：'failed to read dockerfile'

> [+] Building 0.1s (1/2)                                                                                            
>  => [internal] load build definition from Dockerfile                                                          0.0s
>  => => transferring dockerfile: 2B                                                                            0.0s
> failed to solve with frontend dockerfile.v0:  **failed to read dockerfile**: open /var/lib/docker/tmp/buildkit-mount347659786/Dockerfile: no such file or directory

then, I touch the 'dockerfile' and fill docker command in it  to solve it . However, the following error occurred.

> 
>  => [internal] load build definition from Dockerfile                                                          0.0s
> ...
>  => [stage-5 1/3] FROM docker.io/library/nginx:alpine@sha256:686aac2769fd6e7bab67663fd38750c135b72d993d0bb0a  0.0s
>  => [internal] load build context                                                                             0.4s
>  => => transferring context: 10.90MB                                                                          0.4s
>  => [base 1/4] FROM docker.io/library/python:alpine@sha256:964a1afa20dd4a3723002560124dd96f2a9e853f7ef5b86f5  0.0s
>  => CACHED [app-base 2/8] RUN apk add --no-cache python g++ make                                              0.0s
>  => CACHED [app-base 3/8] WORKDIR /app                                                                        0.0s
>  => ERROR [app-base 4/8] COPY app/package.json app/yarn.lock ./                                               0.0s
>  => CACHED [app-base 5/8] RUN yarn install                                                                    0.0s
>  => ERROR [app-base 6/8] COPY app/spec ./spec                                                                 0.0s
>  => ERROR [app-base 7/8] COPY app/src ./src                                                                   0.0s
>  => CACHED [base 2/4] WORKDIR /app                                                                            0.0s
>  => ERROR [base 3/4] COPY requirements.txt .                                                                  0.0s

**Comment by 24kGarry** [comment]
> What errors do you encounter? when i try to build the container, i receive the initial posted error.

firstly, when I docker build it , it can't generate the 'dockerfile' and reports the error：'failed to read dockerfile'

>  [+] Building 0.1s (1/2)
>  => [internal] load build definition from Dockerfile 0.0s
>  => => transferring dockerfile: 2B 0.0s
>  failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount347659786/Dockerfile: no such file or directory

 then, I touch the 'dockerfile' and fill docker command in it to solve that error . However, the following error occurred.

> => [internal] load build definition from Dockerfile 0.0s
> ...
> => [stage-5 1/3] FROM docker.io/library/nginx:alpine@sha256:686aac2769fd6e7bab67663fd38750c135b72d993d0bb0a 0.0s
> => [internal] load build context 0.4s
> => => transferring context: 10.90MB 0.4s
> => [base 1/4] FROM docker.io/library/python:alpine@sha256:964a1afa20dd4a3723002560124dd96f2a9e853f7ef5b86f5 0.0s
> => CACHED [app-base 2/8] RUN apk add --no-cache python g++ make 0.0s
> => CACHED [app-base 3/8] WORKDIR /app 0.0s
> => **ERROR [app-base 4/8] COPY app/package.json app/yarn.lock ./ 0.0s**
> => CACHED [app-base 5/8] RUN yarn install 0.0s
> => **ERROR [app-base 6/8] COPY app/spec ./spec 0.0s**
> => **ERROR [app-base 7/8] COPY app/src ./src 0.0s**
> => CACHED [base 2/4] WORKDIR /app 0.0s
> => **ERROR [base 3/4] COPY requirements.txt . 0.0s**

**Comment by olafbuitelaar** [comment]
This seems to be a complete different Dockerfile than i posted, since it doesn't contain any COPY commands, while your output shows these, also it appears to be based on alphine instead of debian. While alpine support finally would be great, it's also more difficult since it doesn't use the glibc. And generally requires a bit more work, to make it work.

**Comment by 24kGarry** [comment]
> This seems to be a complete different Dockerfile than i posted, since it doesn't contain any COPY commands, while your output shows these, also it appears to be based on alphine instead of debian. While alpine support finally would be great, it's also more difficult since it doesn't use the glibc. And generally requires a bit more work, to make it work.

Indeed, I will try to use the docker which base on debian to build  the dbm program

**Comment by 24kGarry** [comment]
> > This seems to be a complete different Dockerfile than i posted, since it doesn't contain any COPY commands, while your output shows these, also it appears to be based on alphine instead of debian. While alpine support finally would be great, it's also more difficult since it doesn't use the glibc. And generally requires a bit more work, to make it work.
> 
> Indeed, I will try to use the docker which base on debian to build the dbm program

This is a bug that has been fixed. Switch to the latest `1.7.0-SNAPSHOT` development branch to run successfully, 
you can run it again by `1.7.0-SNAPSHOT`

**Comment by olafbuitelaar** [comment]
Great the build works now, thanks!
