### ISSUE TITLE
Bug report for format sql

### ISSUE THREAD

**Issue by wangyunan123** [EdurtIO/dbm#50]
When I format the sql, the error is as follows：

**> TypeError: Cannot read property 'formatter' of null
>     at t.b (renderer.js:1)
>     at r.handlerFormat (68.js:1)
>     at click (68.js:1)
>     at ie (renderer.js:1)
>     at r.a (renderer.js:1)
>     at ie (renderer.js:1)
>     at r.e.$emit (renderer.js:1)
>     at r.handleClick (renderer.js:1)
>     at ie (renderer.js:1)
>     at HTMLButtonElement.a (renderer.js:1)**

**Comment by qianmoQ** [comment]
Fix
