### ISSUE TITLE
Refactoring the underlying technology architecture

### ISSUE THREAD

**Issue by qianmoQ** [EdurtIO/dbm#54]
We're abandoning VUE and refactoring with Angular and Typescript, and we're coming out with new versions!!

**Comment by qianmoQ** [comment]
#### Management  DataSource

- [x] Add data source
- [x] Add data source list
- [ ] Delete data source
- [ ] Modfy data source

**Comment by qianmoQ** [comment]
@joint-song Monitor --> Query   When is the migration expected to be completed?

**Comment by joint-song** [comment]
> 

Rencently, I'm freaking busy at work. These migration is working in progress, I'll finish it as soon as possible. Idealy, this weekend should be the time.

**Comment by qianmoQ** [comment]
> > 
> 
> Rencently, I'm freaking busy at work. These migration is working in progress, I'll finish it as soon as possible. Idealy, this weekend should be the time.

OK
